headerFiles:
  - rdkafka.h
  - rdkafka_mock.h
headerSearchPaths:
  - resources/ffigen/tmp
libraryFile: librdkafka.so.1
generatorClass: RdKafka\FFIGen\MultiVersionGenerator
outputPath: resources/ffigen/tmp
excludeConstants:
  - /^(?!(FFI|RD)_).*/
excludeMethods:
namespace: RdKafka\FFI