language: php
dist: xenial
sudo: true
services:
  - docker
cache:
  directories:
    - $HOME/.composer/cache
php:
  - 7.4snapshot
addons:
  apt:
    packages:
      - libonig-dev
      - libffi-dev
  hosts:
    - kafka
env:
  - LIBRDKAFKA_VERSION=v1.0.0
#  - LIBRDKAFKA_VERSION=master
script:
  - ./travis.sh
  - composer update --prefer-lowest --prefer-stable --no-interaction --no-suggest
  - docker-compose up -d kafka
  - php vendor/bin/phpunit
after_script:
  - docker-compose down
