language: minimal
dist: xenial
sudo: true
services:
  - docker
cache:
  directories:
    - $HOME/.composer/cache
env:
  global:
    - CC_TEST_REPORTER_ID=c543ca814944c789fa9a5ee4c553866eee2e7498d1644258575a24bc05302641

jobs:
  allow_failures:
    - name: "librdkafka master"
  include:
    - &STANDARD_TEST_JOB
      stage: Test
      name: "librdkafka v1.0.1"
      env: LIBRDKAFKA_VERSION=v1.0.1

      before_script:
        - |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter;
          chmod +x ./cc-test-reporter;
          if [ "$LIBRDKAFKA_VERSION" = "v1.0.1" ]; then ./cc-test-reporter before-build; fi;
      script:
        - |
          set -e;
          docker-compose build --pull --parallel --build-arg LIBRDKAFKA_VERSION="$LIBRDKAFKA_VERSION";
          docker-compose up -d kafka;
          sleep 10s;
          docker-compose run --user $(id -u):$(id -g) --rm --no-deps -v $HOME/.composer/cache:/tmp/.composer php74 composer update --prefer-stable --no-interaction --no-suggest;
          docker-compose run --user $(id -u):$(id -g) --rm php74 php examples/create-topic.php -ttest -p1 -r1;
          docker-compose run --user $(id -u):$(id -g) --rm php74 php examples/create-topic.php -ttest_partitions -p3 -r1;
          docker-compose run --user $(id -u):$(id -g) --rm php74 vendor/bin/phpunit --coverage-text --coverage-clover=clover.xml;
      after_script:
        - |
          docker-compose down;
          sed -i "s|/app/|`pwd`/|g" clover.xml;
          if [ "$LIBRDKAFKA_VERSION" = "v1.0.1" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi;

    - <<: *STANDARD_TEST_JOB
      env: LIBRDKAFKA_VERSION=v1.1.0
      name: "librdkafka v1.1.0"

    - <<: *STANDARD_TEST_JOB
      env: LIBRDKAFKA_VERSION=v1.2.2
      name: "librdkafka v1.2.2"

    - <<: *STANDARD_TEST_JOB
      env: LIBRDKAFKA_VERSION=v1.3.0
      name: "librdkafka v1.3.0"

    - <<: *STANDARD_TEST_JOB
      env: LIBRDKAFKA_VERSION=master
      name: "librdkafka master"
