language: php
dist: xenial
sudo: true
services:
  - docker
cache:
  directories:
    - $HOME/.composer/cache
php:
  - 7.4snapshot
addons:
  apt:
    packages:
      - libonig-dev
      - libffi-dev
env:
  - LIBRDKAFKA_VERSION=v1.0.0
#  - LIBRDKAFKA_VERSION=master
script:
  - ./travis.sh
#  - echo "ffi.enable=true" >> $HOME/.phpenv/versions/$TRAVIS_PHP_VERSION/etc/php.ini
#   - cat $HOME/.phpenv/versions/$TRAVIS_PHP_VERSION/etc/php.ini
#  - ls -la $HOME/.phpenv/versions/$TRAVIS_PHP_VERSION
#  - which phpize
  - php -v
  - php -m
#  - composer update --prefer-lowest --prefer-stable --no-interaction --no-suggest
#  - docker-compose up -d kafka
#  - php vendor/bin/phpunit
after_script:
#  - docker-compose down
