language: php
dist: xenial
sudo: true
services:
  - docker
cache:
  directories:
    - $HOME/.composer/cache
php:
  - 7.4snapshot
env:
  - LIBRDKAFKA_VERSION=1.0.0
#  - LIBRDKAFKA_VERSION=master
script:
  - ./travis.sh
  - php -m
  - composer update --prefer-lowest --prefer-stable --no-interaction --no-suggest
  - docker-compose up -d kafka
  - php vendor/bin/phpunit
after_script:
  - docker-compose down
