sudo: true
cache:
  directories:
    - $HOME/.composer/cache
addons:
  hosts:
    - kafka
env:
  global:
    - CC_TEST_REPORTER_ID=c543ca814944c789fa9a5ee4c553866eee2e7498d1644258575a24bc05302641

jobs:
  allow_failures:
    - name: "librdkafka master"
    - name: "librdkafka master osx"
    - name: "librdkafka master windows"
  include:
    - &STANDARD_TEST_JOB
      stage: Test
      name: "librdkafka v1.0.1"
      os: linux
      dist: xenial
      language: minimal
      services:
        - docker
      env: LIBRDKAFKA_VERSION=v1.0.1
      before_script:
        - |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter;
          chmod +x ./cc-test-reporter;
          if [ "$LIBRDKAFKA_VERSION" = "v1.0.1" ]; then ./cc-test-reporter before-build; fi;
      script:
        - |
          set -e;
          docker-compose build --pull --parallel --build-arg LIBRDKAFKA_VERSION="$LIBRDKAFKA_VERSION";
          docker-compose up -d kafka;
          sleep 10s;
          docker-compose run --user $(id -u):$(id -g) --rm --no-deps -v $HOME/.composer/cache:/tmp/.composer php74 composer update --prefer-stable --no-interaction --no-suggest;
          docker-compose run --user $(id -u):$(id -g) --rm php74 php examples/create-topic.php -ttest -p1 -r1;
          docker-compose run --user $(id -u):$(id -g) --rm php74 php examples/create-topic.php -ttest_partitions -p3 -r1;
          docker-compose run --user $(id -u):$(id -g) --rm php74 vendor/bin/phpunit --coverage-text --coverage-clover=clover.xml;
      after_script:
        - |
          docker-compose down;
          sed -i "s|/app/|`pwd`/|g" clover.xml;
          if [ "$LIBRDKAFKA_VERSION" = "v1.0.1" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi;

    - <<: *STANDARD_TEST_JOB
      env: LIBRDKAFKA_VERSION=v1.1.0
      name: "librdkafka v1.1.0"

    - <<: *STANDARD_TEST_JOB
      env: LIBRDKAFKA_VERSION=v1.2.2
      name: "librdkafka v1.2.2"

    - <<: *STANDARD_TEST_JOB
      env: LIBRDKAFKA_VERSION=v1.3.0
      name: "librdkafka v1.3.0"

    - <<: *STANDARD_TEST_JOB
      env: LIBRDKAFKA_VERSION=master
      name: "librdkafka master"

    - env: KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      stage: Test
      name: "librdkafka master osx"
      os: osx
      before_script:
        - |
          brew update;
          brew install php@7.4;
          brew install librdkafka --HEAD;
          brew install composer;
          brew cask install homebrew/cask-versions/adoptopenjdk8;
          brew install kafka;
      script:
        - |
          set -e;
          brew services start zookeeper;
          brew services start kafka;
          sleep 10s;
          composer update --prefer-stable --no-interaction --no-suggest;
          php examples/create-topic.php -ttest -p1 -r1;
          php examples/create-topic.php -ttest_partitions -p3 -r1;
          php vendor/bin/phpunit;
      after_script:
        - |
          brew services stop kafka;
          brew services stop zookeeper;

    - env: KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      stage: Test
      name: "librdkafka master windows"
      os: windows
      language: bash
      before_script:
        - |
          choco install php --version 7.4.1
          php -v
          php -i
          nuget install librdkafka.redist -version 1.3.0
          choco install composer
          wget https://www.apache.org/dyn/closer.cgi?path=/kafka/2.4.0/kafka_2.12-2.4.0.tgz
          tar -xzf kafka_2.12-2.4.0.tgz
          cd kafka_2.12-2.4.0
          dir
          choco install nssm
          nssm install zookeeper .\bin\zookeeper-server-start.bat config\zookeeper.properties
          nssm install kafka .\bin\kafka-server-start.bat config\server.properties
      script:
        - |
          nssm start zookeeper;
          nssm start kafka;
          sleep 10s;
          composer update --prefer-stable --no-interaction --no-suggest;
          php examples/create-topic.php -ttest -p1 -r1;
          php examples/create-topic.php -ttest_partitions -p3 -r1;
          php vendor/bin/phpunit;
      after_script:
        - |
          nssm stop kafka;
          nssm stop zookeeper;

