version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_CREATE_TOPICS: "playground:3:1,test:1:1,test_KafkaConsumer:3:1"
      KAFKA_ADVERTISED_HOST_NAME: "kafka"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 111
    depends_on:
      - zookeeper
    links:
      - zookeeper

  php74:
    image: php74-librdkafka-ffi
    volumes:
      - .:/app
    depends_on:
      - kafka
    links:
      - kafka

  php72:
    image: php72-librdkafka-ext
    volumes:
      - .:/app
    depends_on:
      - kafka
    links:
      - kafka
